### ISSUE TITLE
For those wanting a heartbeat LED if you don't have a display

### ISSUE THREAD

**Issue by xbmcnut** [bruxy70/Irrigation-with-display#4]
Thanks for the code. Working a treat. I don't have a display so wanted to use the blue LED to create a heartbeat indicator so I knew the Sonoff was alive. Quite a steep learning curve with ESPHome but got it working a treat.

```
esphome:
  name: irrigation
  comment: Sonoff 4ch PRO controlling 2 irrigation solenoid valves.
  includes: irrigation.h
  platform: ESP8266
  board: esp01_1m
  on_boot:
    priority: -100
    then:
      - output.turn_on: my_slow_pwm
      - output.set_level:
          id: my_slow_pwm
          level: "50%"
```

And to define the LED

```
output:
  - platform: slow_pwm
    pin: GPIO13
    inverted: true
    id: my_slow_pwm
    period: 1000ms
```
Change the `period` and the `level` to define the duty cycle
